version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/contentlabs
    depends_on:
      - mongo
    networks:
      - app-network
    command: ["npm", "start"]  # Ensure you have a start script in your package.json

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    command: ["npm", "start"]  # Ensure you have a start script in your package.json

networks:
  app-network:

volumes:
  mongo-data: